// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ArticleCard: typeof import('./src/components/ArticleCard.vue')['default']
    BaseButton: typeof import('./src/components/BaseButton.vue')['default']
    Dialog: typeof import('@headlessui/vue')['Dialog']
    DialogOverlay: typeof import('@headlessui/vue')['DialogOverlay']
    ICarbonChevronDown: typeof import('~icons/carbon/chevron-down')['default']
    ICarbonClose: typeof import('~icons/carbon/close')['default']
    ICarbonHome: typeof import('~icons/carbon/home')['default']
    ICarbonInformation: typeof import('~icons/carbon/information')['default']
    ICarbonLogoFacebook: typeof import('~icons/carbon/logo-facebook')['default']
    ICarbonLogoInstagram: typeof import('~icons/carbon/logo-instagram')['default']
    ICarbonLogoTwitter: typeof import('~icons/carbon/logo-twitter')['default']
    ICarbonMenu: typeof import('~icons/carbon/menu')['default']
    ICarbonScatterMatrix: typeof import('~icons/carbon/scatter-matrix')['default']
    IMdiHome: typeof import('~icons/mdi/home')['default']
    MainArticle: typeof import('./src/components/MainArticle.vue')['default']
    Menu: typeof import('@headlessui/vue')['Menu']
    MenuButton: typeof import('@headlessui/vue')['MenuButton']
    MenuItem: typeof import('@headlessui/vue')['MenuItem']
    MenuItems: typeof import('@headlessui/vue')['MenuItems']
    NewArticle: typeof import('./src/components/NewArticles.vue')['default']
    NewArticles: typeof import('./src/components/NewArticles.vue')['default']
    PopularArticles: typeof import('./src/components/PopularArticles.vue')['default']
    RecentArticles: typeof import('./src/components/RecentArticles.vue')['default']
    TransitionChild: typeof import('@headlessui/vue')['TransitionChild']
    TransitionRoot: typeof import('@headlessui/vue')['TransitionRoot']
    WebNavigation: typeof import('./src/components/WebNavigation.vue')['default']
  }
}

export { }
